version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - shared-network
    depends_on:
      - client
      - api
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 4000:4000
    environment:
      - MONGO=${MONGO}
      - JWT=${JWT}
    networks:
      - shared-network

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        - REACT_APP_FIREBASE_KEY=${REACT_APP_FIREBASE_KEY}
    ports:
      - 3000:3000
    environment:
      - REACT_APP_FIREBASE_KEY=${REACT_APP_FIREBASE_KEY}
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
