version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 5000:5000
    networks:
      - shared-network

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
