version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - shared-network
    depends_on:
      - client
      - api
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 4000:4000
    networks:
      - shared-network

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
